apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-rollouts-dev
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-bgd-rollouts-dev
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{clusterName}}-bgd-rollouts'
    spec:
      project: default
      source:
        repoURL: https://github.com/waynedovey/rhacm-day2-gitops-demo
        targetRevision: main
        path: apps/bgd-rollouts
      destination:
        name: '{{clusterName}}'
        namespace: bgd-rollouts-demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
