apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres-frontend-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  database-user: demo
  database-password: demo-password
  database-name: demoapp
