resources:
- 10-placements.yaml
- 20-policyset.yaml
- policy-day2-standard-namespace.yaml
- policy-install-openshift-gitops.yaml
- policy-install-cert-manager.yaml
- policy-install-compliance-operator.yaml
- policy-install-openshift-lightspeed.yaml
- policy-olm-v1-pipelines-version-control.yaml
- 90-placementbindings.yaml
